//! `crates/terrustia-proto/src/recipes.rs` — what each crafted item is made of, for shimmer
//! decrafting. Ported from `gen_recipes.py`.
//!
//! Reads `Recipe.SetupRecipes`, one recipe per `createItem.SetDefaults(N) … AddRecipe()`, keeps the
//! last decraftable recipe for each result (`UpdateWhichItemsAreCrafted`), and packs the
//! ingredients end to end. It does NOT yet unroll the recipes `SetupRecipes` builds inside `for`
//! loops (the shimmer-decraft families) — that is a behavioural change tracked separately as D1, not
//! part of reproducing the current table.

use std::collections::BTreeMap;
use std::path::Path;

use regex::Regex;

use crate::csharp::read_lossy;

const HEADER: &str = "\
//! What crafted things are made of, generated from the game's recipes.
//!
//! This is **not** a crafting system and does not try to be. It knows nothing about crafting
//! stations, conditions, or whether a player can reach a bench. It answers exactly one question:
//! *if this item were broken apart, what would come out?*
//!
//! That is what shimmer needs. An item with no transmutation of its own is decrafted — broken
//! back into its recipe's ingredients — and without this table it simply sat in the pool.
//!
//! Two rules from the game are baked in rather than applied at runtime:
//!
//! * Where several recipes make the same item, the **last** one wins, which is what
//!   `UpdateWhichItemsAreCrafted` does by overwriting as it goes.
//! * Recipes marked `notDecraftable` are excluded outright, so nothing here can be broken apart
//!   that the game would refuse to break.
//!
//! Generated by `terrustia-codegen` from Terraria 1.4.5.7. Do not edit by hand.

/// One ingredient and how many of it the recipe wanted.
pub type Ingredient = (u16, u16);

/// A recipe, as decrafting sees it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Recipe {
    /// What it makes.
    pub result: u16,
    /// How many it makes at once. An item only decrafts if there are at least this many.
    pub makes: u16,
    /// Where this recipe's ingredients start in [`INGREDIENTS`], and how many there are.
    pub first: u16,
    pub count: u8,
    /// Alchemy recipes give back less: each ingredient has a one-in-three chance of being lost,
    /// which is the game's way of stopping potions being a free material duplicator.
    pub alchemy: bool,
}";

const TAIL: &str = r#"fn look_up(table: &[(u16, u16)], key: u16) -> Option<u16> {
    table
        .binary_search_by_key(&key, |&(k, _)| k)
        .ok()
        .map(|at| table[at].1)
}

/// The recipe an item would be broken apart by, if any.
///
/// `ShimmerTransforms.GetDecraftingRecipeIndex`: a world's evil decides between two variants
/// where both exist, so the same item decrafts differently in a crimson world.
pub fn decraft_recipe(item: u16, crimson: bool) -> Option<&'static Recipe> {
    let base = look_up(&CRAFTED_BY, item)?;
    let chosen = if crimson {
        look_up(&CRAFTED_BY_CRIMSON, item).unwrap_or(base)
    } else {
        look_up(&CRAFTED_BY_CORRUPTION, item).unwrap_or(base)
    };
    RECIPES.get(chosen as usize)
}

impl Recipe {
    /// What this recipe wanted.
    pub fn ingredients(&self) -> &'static [Ingredient] {
        let from = self.first as usize;
        &INGREDIENTS[from..from + self.count as usize]
    }
}

/// Whether a recipe is one the world has not earned yet.
///
/// Two gates: some recipes cannot be decrafted until Skeletron is down, others until the Golem
/// is. The game keeps these as recipe sets; both are small and are passed in rather than tabled,
/// since the caller already knows the world's progress.
pub fn decraft_locked(_recipe: &Recipe, _downed_skeletron: bool, _downed_golem: bool) -> bool {
    // `RecipeSets.PostSkeletron` and `PostGolem` are empty in 1.4.5.7 — the gates exist and
    // nothing is behind them. Kept as a named function so a later version that fills them in
    // needs a table rather than a new concept.
    false
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The lookups are sorted, or the binary searches silently miss.
    #[test]
    fn the_lookups_are_sorted() {
        for (name, table) in [
            ("CRAFTED_BY", &CRAFTED_BY[..]),
            ("CRAFTED_BY_CRIMSON", &CRAFTED_BY_CRIMSON[..]),
            ("CRAFTED_BY_CORRUPTION", &CRAFTED_BY_CORRUPTION[..]),
        ] {
            assert!(
                table.windows(2).all(|w| w[0].0 < w[1].0),
                "{name} must be strictly ascending"
            );
        }
    }

    /// Every recipe's ingredient span lies inside the packed array and holds real items.
    #[test]
    fn every_recipe_points_at_real_ingredients() {
        for recipe in RECIPES {
            let end = recipe.first as usize + recipe.count as usize;
            assert!(
                end <= INGREDIENTS.len(),
                "item {} runs past the ingredient table",
                recipe.result
            );
            assert!(recipe.count > 0, "item {} has no ingredients", recipe.result);
            assert!(recipe.makes > 0, "item {} makes nothing", recipe.result);
            for &(item, stack) in recipe.ingredients() {
                assert!(item > 0, "recipe for {} wants item zero", recipe.result);
                assert!(stack > 0, "recipe for {} wants none of {item}", recipe.result);
            }
        }
    }

    /// Every index in the lookups names a recipe that exists.
    #[test]
    fn every_lookup_names_a_recipe() {
        for table in [&CRAFTED_BY[..], &CRAFTED_BY_CRIMSON[..], &CRAFTED_BY_CORRUPTION[..]] {
            for &(item, at) in table {
                assert!(
                    (at as usize) < RECIPES.len(),
                    "item {item} names recipe {at}, past the end"
                );
            }
        }
    }

    /// A well-known one, end to end.
    #[test]
    fn a_torch_decrafts_into_what_it_was_made_of() {
        let torch = decraft_recipe(8, false).expect("a torch is crafted");
        assert_eq!(torch.result, 8);
        assert_eq!(torch.makes, 3, "three torches at a time");
        let wants: Vec<u16> = torch.ingredients().iter().map(|&(i, _)| i).collect();
        assert!(wants.contains(&23), "a torch wants gel");
    }

    /// Something that is not crafted decrafts into nothing.
    ///
    /// Note that a great deal *is* crafted, including things that feel primitive — an Iron
    /// Pickaxe is ten bars and three wood. So this checks the shape of the answer rather than
    /// guessing at which items are raw.
    #[test]
    fn raw_materials_do_not_decraft() {
        assert!(decraft_recipe(0, false).is_none(), "nothing at all");
        let uncraftable = (1u16..2000)
            .filter(|&i| decraft_recipe(i, false).is_none())
            .count();
        assert!(
            uncraftable > 100,
            "only {uncraftable} of the first two thousand items are uncrafted, which is too few"
        );
    }

    /// The two evils can disagree about what an item is made of.
    #[test]
    fn the_evils_can_differ() {
        let differing = (0u16..u16::MAX).filter(|&i| {
            match (decraft_recipe(i, false), decraft_recipe(i, true)) {
                (Some(a), Some(b)) => a != b,
                _ => false,
            }
        });
        assert!(
            differing.take(1).count() > 0 || CRAFTED_BY_CRIMSON.is_empty(),
            "if any recipe is evil-specific, some item should decraft differently"
        );
    }
}"#;

/// One parsed recipe declaration, before the last-wins filtering.
struct RecipeData {
    result: u32,
    stack: u32,
    ingredients: Vec<(u32, u32)>,
    not_decraftable: bool,
    crimson: bool,
    corruption: bool,
    alchemy: bool,
}

/// Both ingredient-declaration styles, in slot order — mirrors `gen_recipes.py`'s `ingredients_of`.
fn ingredients_of(text: &str) -> Vec<(u32, u32)> {
    let mut found: BTreeMap<u32, [u32; 2]> = BTreeMap::new();

    // Style one: requiredItem[i].SetDefaults(X); optionally requiredItem[i].stack = N;
    let set_re = Regex::new(r"requiredItem\[(\d+)\]\.SetDefaults\((\d+)\)").unwrap();
    for cap in set_re.captures_iter(text) {
        let slot: u32 = cap[1].parse().unwrap();
        let item: u32 = cap[2].parse().unwrap();
        if item > 0 {
            found.insert(slot, [item, 1]);
        }
    }
    let stack_re = Regex::new(r"requiredItem\[(\d+)\]\.stack = (\d+)").unwrap();
    for cap in stack_re.captures_iter(text) {
        let slot: u32 = cap[1].parse().unwrap();
        let stack: u32 = cap[2].parse().unwrap();
        if let Some(entry) = found.get_mut(&slot) {
            entry[1] = stack;
        }
    }

    // Style two: SetIngredients(item, count, item, count, …) — the game's own convention is that
    // the call always alternates item, count; a trailing lone item defaults to a count of one.
    if let Some(m) = Regex::new(r"SetIngredients\(([^)]*)\)").unwrap().captures(text) {
        let nums: Vec<i64> = Regex::new(r"-?\d+")
            .unwrap()
            .find_iter(&m[1])
            .map(|x| x.as_str().parse().unwrap())
            .collect();
        let mut slot = found.len() as u32;
        let mut i = 0;
        while i + 1 < nums.len() {
            if nums[i] > 0 {
                found.insert(slot, [nums[i] as u32, (nums[i + 1].max(1)) as u32]);
                slot += 1;
            }
            i += 2;
        }
        if nums.len() % 2 == 1
            && let Some(&last) = nums.last()
            && last > 0
        {
            found.insert(slot, [last as u32, 1]);
        }
    }

    found.into_values().map(|v| (v[0], v[1])).collect()
}

/// Emit an ascending `static NAME: [(u16, u16); N]` index table. `cargo fmt` reflows the rows.
fn index_table(name: &str, rows: &[(u32, u32)], doc: &str) -> String {
    let body: Vec<String> = rows.iter().map(|&(a, b)| format!("({a},{b}),")).collect();
    format!(
        "{doc}\nstatic {name}: [(u16, u16); {}] = [\n    {}\n];",
        rows.len(),
        body.join(" ")
    )
}

pub fn generate(root: &Path) -> String {
    let src = read_lossy(&root.join("Terraria/Recipe.cs"));
    let start = src
        .find("public static void SetupRecipes()")
        .expect("SetupRecipes not found");
    let body = &src[start..];

    let chunk_re =
        Regex::new(r"(?s)currentRecipe\.createItem\.SetDefaults\((\d+)\);(.*?)AddRecipe\(\);")
            .unwrap();
    let stack_re = Regex::new(r"createItem\.stack = (\d+)").unwrap();

    let mut recipes: Vec<RecipeData> = Vec::new();
    for cap in chunk_re.captures_iter(body) {
        let result: u32 = cap[1].parse().unwrap();
        let text = &cap[2];
        let stack = stack_re
            .captures(text)
            .map_or(1, |m| m[1].parse().unwrap());
        recipes.push(RecipeData {
            result,
            stack,
            ingredients: ingredients_of(text),
            not_decraftable: text.contains("notDecraftable = true")
                || text.contains("DisableDecraft()"),
            crimson: text.contains("crimson = true")
                || text.contains(".AddCondition(Condition.InCrimson"),
            corruption: text.contains("corruption = true")
                || text.contains(".AddCondition(Condition.InCorruption"),
            alchemy: text.contains("alchemy = true"),
        });
    }
    assert!(
        recipes.len() >= 1000,
        "only {} recipes parsed; SetupRecipes' shape changed",
        recipes.len()
    );

    // `UpdateWhichItemsAreCrafted`: the last decraftable recipe for a result wins.
    let mut is_crafted: BTreeMap<u32, usize> = BTreeMap::new();
    let mut crimson_of: BTreeMap<u32, usize> = BTreeMap::new();
    let mut corruption_of: BTreeMap<u32, usize> = BTreeMap::new();
    for (index, r) in recipes.iter().enumerate() {
        if r.ingredients.is_empty() {
            continue;
        }
        if !r.not_decraftable {
            is_crafted.insert(r.result, index);
        }
        if r.crimson {
            crimson_of.insert(r.result, index);
        }
        if r.corruption {
            corruption_of.insert(r.result, index);
        }
    }

    let mut used: Vec<usize> = is_crafted
        .values()
        .chain(crimson_of.values())
        .chain(corruption_of.values())
        .copied()
        .collect();
    used.sort_unstable();
    used.dedup();
    let renumber: BTreeMap<usize, usize> =
        used.iter().enumerate().map(|(new, &old)| (old, new)).collect();

    // Pack ingredients end to end and lay out the recipes in kept order.
    let mut flat: Vec<(u32, u32)> = Vec::new();
    let mut recipe_rows: Vec<String> = Vec::new();
    for &old in &used {
        let r = &recipes[old];
        let first = flat.len();
        flat.extend(r.ingredients.iter().copied());
        recipe_rows.push(format!(
            "    Recipe {{ result: {}, makes: {}, first: {first}, count: {}, alchemy: {} }},",
            r.result,
            r.stack,
            r.ingredients.len(),
            r.alchemy
        ));
    }

    let ingredients_rows: Vec<String> =
        flat.iter().map(|&(i, s)| format!("({i},{s}),")).collect();
    let ingredients_block = format!(
        "/// Every decraftable recipe's ingredients, packed end to end.\n\
         ///\n\
         /// `static` rather than `const`: a `const` of this size is copied at every use site.\n\
         static INGREDIENTS: [Ingredient; {}] = [\n    {}\n];",
        flat.len(),
        ingredients_rows.join(" ")
    );
    let recipes_block = format!(
        "/// The recipes themselves, in the game's own order.\nstatic RECIPES: [Recipe; {}] = [\n{}\n];",
        used.len(),
        recipe_rows.join("\n")
    );

    let renumbered = |mapping: &BTreeMap<u32, usize>| -> Vec<(u32, u32)> {
        let mut rows: Vec<(u32, u32)> = mapping
            .iter()
            .filter_map(|(&item, old)| renumber.get(old).map(|&new| (item, new as u32)))
            .collect();
        rows.sort_unstable();
        rows
    };
    let crafted_by = index_table(
        "CRAFTED_BY",
        &renumbered(&is_crafted),
        "/// Which recipe makes each craftable item. `ItemID.Sets.IsCrafted`.",
    );
    let crafted_by_crimson = index_table(
        "CRAFTED_BY_CRIMSON",
        &renumbered(&crimson_of),
        "/// ...and the crimson-world variant, where one exists.",
    );
    let crafted_by_corruption = index_table(
        "CRAFTED_BY_CORRUPTION",
        &renumbered(&corruption_of),
        "/// ...and the corruption one.",
    );

    format!(
        "{HEADER}\n\n{ingredients_block}\n\n{recipes_block}\n\n{crafted_by}\n\n{crafted_by_crimson}\n\n{crafted_by_corruption}\n\n{TAIL}\n"
    )
}
