//! Check a generated world against the one Terraria made from the same seed.
//!
//! This is the instrument the whole world-generation port is steered by. A `.wld` records the
//! state of the world's random generator after every one of its generation passes, and that
//! generator is never reseeded — so the value after pass N is a fingerprint of every draw made by
//! passes one to N. Run the port to pass N and compare, and either the whole prefix is exactly
//! right or the first pass that disagrees is named.
//!
//! Without this the port is unfalsifiable until all hundred and six passes are done. With it,
//! each one is checkable on its own.
//!
//! ```sh
//! cargo run --release -p terrustia --example genparity -- reference.wld
//! ```
//!
//! Give it a world generated by Terraria. It reads the seed and the manifest out of the file, so
//! nothing else has to be supplied.

use std::{env, process::ExitCode};

use terrustia::world::{wld, worldgen::manifest::Manifest, worldgen::rand::translate_seed};

fn main() -> ExitCode {
    let Some(path) = env::args().nth(1) else {
        eprintln!("usage: genparity <reference.wld>");
        eprintln!();
        eprintln!("a world generated by Terraria, whose seed and pass record are read from it");
        return ExitCode::FAILURE;
    };

    let bytes = match std::fs::read(&path) {
        Ok(bytes) => bytes,
        Err(e) => {
            eprintln!("could not read {path}: {e}");
            return ExitCode::FAILURE;
        }
    };
    let world = match wld::parse(&bytes) {
        Ok(world) => world,
        Err(e) => {
            eprintln!("could not parse {path}: {e}");
            return ExitCode::FAILURE;
        }
    };
    let Some(preserved) = world.preserved.as_ref() else {
        eprintln!("that world has no preserved header, so it carries no record");
        return ExitCode::FAILURE;
    };
    let Some(manifest) = Manifest::from_header(&preserved.header_bytes) else {
        eprintln!("that world carries no generation manifest");
        eprintln!("it was probably not made by Terraria — try a world generated in the game");
        return ExitCode::FAILURE;
    };

    let seed = translate_seed(&world.seed_text);
    println!("reference: {}", path);
    println!(
        "  world     {} ({}x{})",
        world.name,
        world.width(),
        world.height()
    );
    println!("  built by  {}", manifest.version.as_deref().unwrap_or("?"));
    println!("  seed      {:?} -> {seed}", world.seed_text);
    println!(
        "  evil      {}",
        if world.crimson {
            "crimson"
        } else {
            "corruption"
        }
    );
    println!(
        "  passes    {} recorded, {} ran, {} skipped",
        manifest.passes.len(),
        manifest.ran().count(),
        manifest.passes.iter().filter(|p| p.skipped).count()
    );
    let hashed = manifest.passes.iter().filter(|p| p.hash.is_some()).count();
    println!("  hashes    {hashed} of {} passes", manifest.passes.len());
    if hashed <= 1 {
        println!(
            "            (only the last one, which is the default; the game records a hash for"
        );
        println!("             every pass when its own generation debugger is switched on)");
    }
    println!();

    // Run the port as far as it goes, and compare pass by pass.
    let outcome = terrustia::world::worldgen::compare_against(&manifest, seed, &world);
    match outcome.first_divergence {
        None if outcome.checked == 0 => {
            println!("no passes are implemented yet, so nothing was checked.");
            println!(
                "the first to write is {:?}, whose generator should read {} afterwards.",
                manifest
                    .passes
                    .first()
                    .map(|p| p.name.as_str())
                    .unwrap_or("?"),
                manifest.passes.first().map(|p| p.rand_next).unwrap_or(0),
            );
            ExitCode::SUCCESS
        }
        None => {
            println!(
                "all {} implemented passes match the reference.",
                outcome.checked
            );
            if outcome.checked < manifest.ran().count() {
                let next = manifest.ran().nth(outcome.checked);
                println!(
                    "next to write: {:?}",
                    next.map(|p| p.name.as_str()).unwrap_or("?")
                );
            }
            ExitCode::SUCCESS
        }
        Some(diverged) => {
            println!(
                "first divergence at pass {}: {:?}",
                diverged.index + 1,
                diverged.name
            );
            println!("  reference generator reads {}", diverged.expected);
            println!("  ours reads               {}", diverged.got);
            println!();
            println!("every pass before it matches, so that pass is the one that is wrong.");
            println!("a difference here is a difference in how many numbers it drew, or in what");
            println!("order — not necessarily in the tiles it wrote.");
            ExitCode::FAILURE
        }
    }
}
