//! Regression tests for the loot and stat tables, kept outside the tables themselves.
//!
//! Every table these touch is regenerated by `just regen`, so an assertion written *inside* one of
//! them is rewritten by the next run and cannot guard anything. These live here instead, and each
//! one names a specific thing the 2026-08-30 audit found the generators had lost, with the vanilla
//! source that says what the right answer is. Every one of them fails against the generators as
//! they were.

use terrustia_proto::conditional_drops::{Conditions, conditional, treasure_bag};
use terrustia_proto::{banners, npc_drops, projectile_data, travel_shop};

/// The 25 slime types `ItemDropRule.Gel` covers, from `ItemDropDatabase.cs:962-1088`.
const SLIMES_THAT_DROP_GEL: [u16; 25] = [
    1, 16, 81, 122, 138, 141, 147, 183, 184, 187, 204, 225, 244, 302, 333, 334, 335, 336, 433, 433,
    535, 537, 658, 659, 660,
];

fn drops_item(npc_type: u16, item: u16) -> bool {
    npc_drops::drops(npc_type)
        .iter()
        .any(|chain| chain.iter().any(|d| d.item == item))
}

/// Gel. `ItemDropRule.Gel` was in neither the generator's flat list nor its exclusion list, so
/// item 23 dropped from nothing at all: no torches, and no Slime Crown, so King Slime could not be
/// summoned.
#[test]
fn every_slime_drops_gel() {
    for npc in SLIMES_THAT_DROP_GEL {
        assert!(drops_item(npc, 23), "npc {npc} drops no gel");
    }
    assert!(drops_item(676, 23), "the Corrupt Slime Spawn drops gel");
    // The amounts are the game's own, not a flat 1.
    let king_slime_food = npc_drops::drops(244)
        .iter()
        .flat_map(|chain| chain.iter())
        .find(|d| d.item == 23)
        .expect("npc 244 drops gel");
    assert_eq!((king_slime_food.min, king_slime_food.max), (1, 20));
}

/// The Lunar Towers' fragments, `ItemDropDatabase.cs:608-629`. Without them the entire lunar tier
/// is uncraftable and there is no Zenith path.
#[test]
fn the_lunar_pillars_drop_their_fragments() {
    for (tower, fragment) in [(517u16, 3458u16), (422, 3456), (507, 3457), (493, 3459)] {
        let classic = conditional(tower, Conditions::default());
        let rule = classic
            .iter()
            .find(|d| d.item == fragment)
            .unwrap_or_else(|| panic!("tower {tower} drops no fragment {fragment}"));
        assert_eq!((rule.min, rule.max), (12, 60), "classic range");

        let expert = conditional(
            tower,
            Conditions {
                expert: true,
                ..Default::default()
            },
        );
        let rule = expert
            .iter()
            .find(|d| d.item == fragment)
            .expect("and in expert");
        assert_eq!((rule.min, rule.max), (24, 100), "expert range");
    }
}

/// The Terraprisma is gated on `Conditions.EmpressOfLightIsGenuinelyEnraged`
/// (`ItemDropDatabase.cs:332-333`), not handed out for every Empress kill. The generator read the
/// gate as an unconditional rule because it had been assigned to a local first.
#[test]
fn the_terraprisma_is_not_an_unconditional_drop() {
    assert!(!drops_item(636, 5005));
}

/// Betsy, the Empress, Queen Slime and Deerclops each suppress their classic loot in expert, so
/// with no treasure bag they dropped literally nothing there.
#[test]
fn the_four_late_bosses_have_treasure_bags() {
    for (boss, bag) in [(551u16, 3860u16), (636, 4782), (657, 4957), (668, 5111)] {
        assert_eq!(treasure_bag(boss), Some(bag));
        let expert = conditional(
            boss,
            Conditions {
                expert: true,
                ..Default::default()
            },
        );
        assert!(
            expert.iter().any(|d| d.item == bag),
            "boss {boss} drops nothing at all in expert"
        );
    }
}

/// The 29 master-mode relics and 28 pets and mounts, which the generator excluded outright and no
/// other table carried.
#[test]
fn master_mode_relics_and_pets_are_reachable() {
    let mut items: Vec<u16> = (0..700u16)
        .flat_map(npc_drops::master_drops)
        .map(|d| d.item)
        .collect();
    items.sort_unstable();
    items.dedup();
    assert_eq!(items.len(), 57, "29 relics and 28 pets and mounts");

    let master = Conditions {
        master: true,
        ..Default::default()
    };
    // King Slime's relic and pet, `ItemDropDatabase.cs:397-398`.
    let loot = conditional(50, master);
    assert!(loot.iter().any(|d| d.item == 4929 && d.one_in == 1));
    assert!(loot.iter().any(|d| d.item == 4797 && d.one_in == 4));
    // ...and neither of them in a classic world.
    let classic = conditional(50, Conditions::default());
    assert!(!classic.iter().any(|d| d.item == 4929 || d.item == 4797));
}

/// `BannerSystem.BannerToItem`'s ladder (`BannerSystem.cs:341-401`). Three rungs were missing, so
/// fifteen banner indices handed over the wrong item: fifty Orca kills paid a Quad Barrel Shotgun.
#[test]
fn the_banner_ladder_has_all_of_its_rungs() {
    assert_eq!(banners::banner_item(292), 5673);
    assert_eq!(banners::banner_item(291), 5672);
    assert_eq!(banners::banner_item(290), 5651);
    assert_eq!(banners::banner_item(289), 5352);
    for banner in 276..=288u16 {
        assert_eq!(banners::banner_item(banner), 4965 + banner - 276);
    }
    // The rung below still starts where it did.
    assert_eq!(banners::banner_item(275), 4688);
    assert_eq!(banners::banner_item(274), 4687);
}

/// The two Zapinators (`Chest.cs:1168-1175`). Their candidate guards on a parenthesised
/// disjunction, which the shop generator's `[^)]*` condition tail could not span, so the whole
/// candidate was dropped and the merchant never sold either.
#[test]
fn the_travelling_merchant_stocks_both_zapinators() {
    assert!(travel_shop::OFFERS.iter().any(|o| o.item == 4347), "Gray");
    let orange = travel_shop::OFFERS
        .iter()
        .find(|o| o.item == 4348)
        .expect("Orange");
    assert_eq!(
        orange.needs,
        travel_shop::Needs(travel_shop::Needs::HARDMODE)
    );
}

/// Every yoyo, `Projectile.cs:6023-6060`. They live in `else if (type >= A && type <= B)` arms the
/// projectile generator's chain regex could not see, so the server could not fire any of them.
#[test]
fn every_yoyo_has_stats() {
    for kind in (541..=555u16).chain(562..=564) {
        let stats = projectile_data::projectile_stats(kind)
            .unwrap_or_else(|| panic!("projectile {kind} is missing"));
        assert_eq!((stats.width, stats.height), (16, 16));
        // `DefaultToYoyo()` (`Projectile.cs:10766-10773`), inlined by the generator.
        assert_eq!(stats.ai_style, 99, "projectile {kind}");
        assert_eq!(stats.penetrate, -1, "projectile {kind}");
    }
    // Plantera's spore gas and the Pygmy minions, from the same class of arm.
    for kind in [569u16, 570, 571, 191, 192, 193, 194, 230, 986] {
        assert!(projectile_data::projectile_stats(kind).is_some(), "{kind}");
    }
}

/// `hostile = true` inside `if (Main.getGoodWorld)` (`Projectile.cs:1260-1271` and its siblings) is
/// a seed feature. Read unconditionally it marked a headstone hostile in an ordinary world, which
/// is what `hostile` is checked for: whether a client may claim to own one.
#[test]
fn graveyard_props_are_not_hostile() {
    for kind in [12u16, 43, 201, 202, 203, 204, 205] {
        let stats = projectile_data::projectile_stats(kind).expect("defined");
        assert!(!stats.hostile, "projectile {kind} ({}) ", stats.name);
    }
    // Greek Fire really is hostile, and got its whole arm read from a nested `if` before.
    for kind in [326u16, 327, 328] {
        let stats = projectile_data::projectile_stats(kind).expect("defined");
        assert!(stats.hostile, "projectile {kind}");
        assert_eq!(stats.ai_style, 14);
        assert_eq!(stats.time_left, 360);
    }
}

/// The three `DD2FlameBurstTower` tiers differ only inside a `switch (type)`
/// (`Projectile.cs:7141-7154`), which the generator read flat, giving all three the last case.
#[test]
fn the_flame_burst_towers_keep_their_own_sizes() {
    let size = |kind: u16| {
        let s = projectile_data::projectile_stats(kind).expect("defined");
        (s.width, s.height)
    };
    assert_eq!(size(663), (30, 54));
    assert_eq!(size(665), (28, 58));
    assert_eq!(size(667), (28, 60));
}

/// Four items that had no source anywhere in the project, each lost to a different generator gap.
#[test]
fn four_orphaned_items_have_a_source_again() {
    // `ScalingWithOnlyBadLuck` was in neither the flat nor the excluded list.
    assert!(drops_item(53, 4271) && drops_item(536, 4271), "Bloody Tear");
    // The Ice Mimic's rule is built into a local one line before its registration.
    assert!(drops_item(629, 1312), "Toy Sled");
    // `new CommonDropNotScalingWithLuck(...)`, spelled out rather than called through
    // `ItemDropRule`.
    assert!(drops_item(576, 3865) && drops_item(577, 3865), "DD2 drop");
    // `Conditions.DontStarveIsNotUp` is true in every ordinary world.
    let bat = conditional(49, Conditions::default());
    assert!(bat.iter().any(|d| d.item == 5097 && d.one_in == 300));
}
