//! Choose what the sky and the treetops look like.
//!
//! None of this changes a rule of play — no routine anywhere reads a background style — but all of
//! it goes out in packet 7, and a world that reports nought for the lot serves every biome the
//! same flat backdrop and every tree the same top. Terraria has rolled these since 1.4; a world
//! that has not is visibly not a Terraria world.
//!
//! Ported from `WorldGen.RandomizeBackgrounds` and `TreeTopsInfo.CopyExistingWorldInfo`. The
//! curious shape of the forest roll — draw, and redraw on a 0, 1 or 2 — is the game's own way of
//! making the plainer backdrops rarer, and is kept rather than smoothed out.

use crate::world::{World, wld::Scenery};

use super::rand::UnifiedRandom;

/// Roll the thirteen background styles and the thirteen tree tops that follow from them.
pub fn choose(world: &mut World, rand: &mut UnifiedRandom) {
    let mut bg = [0u8; 13];

    // The four forest variants, each distinct from the ones before it. The game redraws until it
    // gets a fresh one; with a dozen-odd styles to choose from that ends quickly, but the attempt
    // is bounded anyway so a future table of one cannot hang a world generation.
    for taken in 0..4 {
        let mut style = forest(rand);
        for _ in 0..64 {
            if !bg[..taken].contains(&style) {
                break;
            }
            style = forest(rand);
        }
        bg[taken] = style;
    }

    bg[Scenery::CORRUPT] = corruption(rand);
    bg[Scenery::JUNGLE] = rand.next_max(7) as u8;
    bg[Scenery::SNOW] = snow(rand);
    bg[Scenery::HALLOW] = rand.next_max(6) as u8;
    bg[Scenery::CRIMSON] = rand.next_max(7) as u8;
    bg[Scenery::DESERT] = desert(rand);
    bg[Scenery::OCEAN] = rand.next_max(8) as u8;
    bg[Scenery::MUSHROOM] = rand.next_max(5) as u8;
    bg[Scenery::UNDERWORLD] = rand.next_max(3) as u8;

    world.backgrounds = bg;
    world.tree_tops = tree_tops(&bg, world.tree_style);
    // A quiet sky reads as a bug rather than as weather, so a world starts with some cloud.
    world.num_clouds = rand.next_range(10, 60) as u8;
}

/// The tree-top variations a world starts with.
///
/// Not rolled: the game seeds them from what it already decided, so the forest areas take the four
/// tree styles and every other area takes its own biome's backdrop. Split out and public because
/// it is checkable — a real world's packet 7 has to satisfy this relation, and one does.
pub fn tree_tops(backgrounds: &[u8; 13], tree_style: [u8; 4]) -> [u8; 13] {
    let mut tops = *backgrounds;
    tops[..4].copy_from_slice(&tree_style);
    tops
}

/// `RollRandomForestBGStyle`: the plainer styles are drawn again, so they come up half as often.
fn forest(rand: &mut UnifiedRandom) -> u8 {
    const STYLES: i32 = 14;
    let mut style = rand.next_max(STYLES);
    if (style == 1 || style == 2) && rand.next_max(2) == 0 {
        style = rand.next_max(STYLES);
    }
    if style == 0 {
        style = rand.next_max(STYLES);
    }
    if style == 3 && rand.next_max(3) == 0 {
        style = 31;
    }
    if style == 5 && rand.next_max(2) == 0 {
        style = 51;
    }
    if style == 7 && rand.next_max(4) == 0 {
        style = rand.next_range(71, 74);
    }
    style as u8
}

/// `RandomizeBackgrounds_Corruption`: style 5 splits into two variants.
fn corruption(rand: &mut UnifiedRandom) -> u8 {
    match rand.next_max(6) {
        5 if rand.next_max(2) == 0 => 51,
        5 => 52,
        style => style as u8,
    }
}

/// `RandomizeBackgrounds_Desert`: style 5 splits three ways, weighted by an integer division.
fn desert(rand: &mut UnifiedRandom) -> u8 {
    match rand.next_max(6) {
        5 => 51 + (rand.next_max(5) / 2) as u8,
        style => style as u8,
    }
}

/// Snow's styles 2, 3 and 4 each split into two variants on a coin flip.
fn snow(rand: &mut UnifiedRandom) -> u8 {
    let style = rand.next_max(9);
    for base in [2, 3, 4] {
        if style == base && rand.next_max(2) == 0 {
            return if rand.next_max(2) == 0 {
                (base * 10 + 1) as u8
            } else {
                (base * 10 + 2) as u8
            };
        }
    }
    style as u8
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The relation that holds in a real world's packet 7.
    ///
    /// Taken from `ProbeTiny`, generated by a real 1.4.5.8 server: its backgrounds were
    /// `[51, 9, 2, 6, 1, 5, 0, 2, 3, 2, 5, 2, 0]` and its tree styles `[2, 4, 0, 0]`, and its tree
    /// tops came over the wire as `[2, 4, 0, 0, 1, 5, 0, 2, 3, 2, 5, 2, 0]` — the four styles,
    /// then the nine biome backdrops unchanged. This pins that, so the derivation cannot quietly
    /// become a roll of its own.
    #[test]
    fn tree_tops_match_a_real_worlds() {
        let backgrounds = [51, 9, 2, 6, 1, 5, 0, 2, 3, 2, 5, 2, 0];
        assert_eq!(
            tree_tops(&backgrounds, [2, 4, 0, 0]),
            [2, 4, 0, 0, 1, 5, 0, 2, 3, 2, 5, 2, 0]
        );
    }

    #[test]
    fn the_four_forest_backdrops_are_all_different() {
        // The game loops until they are, and four identical skies either side of the spawn is
        // exactly the flatness this pass exists to avoid.
        for seed in 0..200 {
            let mut world = World::empty(4200, 1200, "t");
            let mut rand = UnifiedRandom::new(seed);
            choose(&mut world, &mut rand);
            let forest = &world.backgrounds[..4];
            for (i, a) in forest.iter().enumerate() {
                for b in &forest[i + 1..] {
                    assert_ne!(a, b, "seed {seed}: two forest backdrops are the same");
                }
            }
        }
    }

    #[test]
    fn every_style_is_one_the_game_could_have_rolled() {
        // Guards against a `next_max` bound that has drifted: a style outside the game's own set
        // is one the client has no art for, which draws as nothing at all.
        for seed in 0..200 {
            let mut world = World::empty(4200, 1200, "t");
            let mut rand = UnifiedRandom::new(seed);
            choose(&mut world, &mut rand);

            for slot in 0..4 {
                let style = world.backgrounds[slot];
                assert!(
                    style < 14 || style == 31 || style == 51 || (71..74).contains(&style),
                    "seed {seed}: forest style {style}"
                );
            }
            assert!(matches!(
                world.backgrounds[Scenery::CORRUPT],
                0..=4 | 51 | 52
            ));
            assert!(world.backgrounds[Scenery::JUNGLE] < 7);
            assert!(matches!(
                world.backgrounds[Scenery::SNOW],
                0..=8 | 21 | 22 | 31 | 32 | 41 | 42
            ));
            assert!(world.backgrounds[Scenery::HALLOW] < 6);
            assert!(world.backgrounds[Scenery::CRIMSON] < 7);
            assert!(matches!(world.backgrounds[Scenery::DESERT], 0..=4 | 51..=53));
            assert!(world.backgrounds[Scenery::OCEAN] < 8);
            assert!(world.backgrounds[Scenery::MUSHROOM] < 5);
            assert!(world.backgrounds[Scenery::UNDERWORLD] < 3);
            assert!((10..60).contains(&world.num_clouds));
        }
    }

    #[test]
    fn the_same_seed_gives_the_same_sky() {
        let sky = |seed| {
            let mut world = World::empty(4200, 1200, "t");
            choose(&mut world, &mut UnifiedRandom::new(seed));
            (world.backgrounds, world.tree_tops, world.num_clouds)
        };
        assert_eq!(sky(7), sky(7));
        assert_ne!(sky(7), sky(8));
    }
}
