#!/usr/bin/env bash
#
# Same-world differential: point the real Terraria dedicated server and terrustia at one and the
# same `.wld`, join each with `examples/probe`, and judge the two packet sequences against each
# other.
#
#   ./tools/differential.sh
#
# ## Why the same world, and not two fresh ones
#
# A fresh-versus-fresh run is not a comparison, it is a coincidence detector. Vanilla's `autocreate`
# generates a world with a Guide already living in it; a terrustia `--new` world has no town NPC at
# all. The histograms then differ by three `SyncNPC` (23) and three `NPCBuffs` (54) packets, which
# reads as a protocol fault and is nothing of the kind: it is one world having an NPC and the other
# not. Loading one file into both servers removes that entire class of false positive, and it is
# available today because this repo round-trips a `.wld` byte-for-byte (`examples/roundtrip_wld.rs`).
#
# The file is generated by *vanilla*, not by us, on purpose: a world the game itself wrote is
# certainly one the game will load, so a load failure on our side is our bug and never an argument
# about whose generator is right.
#
# ## What it judges
#
# Three separate things, because they fail for different reasons and are worth different amounts:
#
#   1. ORDER      - the ids both servers send, in the sequence they send them.
#   2. COVERAGE   - ids one server sends and the other never does.
#   3. PAYLOAD    - the byte length of the first frame of each shared id.
#
# Plus one named invariant, which is the reason this script exists: every packet of the join tail
# must precede 129 `FinishedConnectingToServer`. Vanilla sends 129 as the last act of `MessageBuffer`
# case 12 (`MessageBuffer.cs:937`), after `SyncConnectedPlayer` (60, 72, 74), after 139, and long
# after case 8 has sent 101 and 136 (`MessageBuffer.cs:869-870`). 129 means "you are in"; anything
# sent after it reaches a client that has already stopped listening for handshake state.
#
# Exits non-zero when any judged difference is not in the EXPECTED list below.
#
# Requires the real server. Override its path with TERRARIA_SERVER=.

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VANILLA="${TERRARIA_SERVER:-$HOME/Library/Application Support/Steam/steamapps/common/Terraria/Terraria.app/Contents/MacOS/TerrariaServer}"
BIN="$ROOT/target/release/terrustia"
PROBE="$ROOT/target/release/examples/probe"
# Seconds each probe keeps reading after 129. Without a linger a probe stops at 129 exactly as a
# client would, and everything wrongly sent after 129 is invisible to the very tool meant to find it.
LINGER="${DIFF_LINGER:-8}"
SEED="${DIFF_SEED:-1337}"
KEEP="${DIFF_KEEP:-0}"

# Differences that are understood and are not protocol faults. One per line: "<id> <reason>".
# Anything not listed here fails the run.
EXPECTED=$(cat <<'END'
END
)

WORK="$(mktemp -d)"
VSRV=""
OSRV=""
cleanup() {
  # `exit` down the fifo is how vanilla shuts down cleanly; a killed server can sit on its port
  # long enough to break the next run, which is the one failure mode this script must not have.
  [ -n "$VSRV" ] && { echo exit > "$WORK/vfifo" 2>/dev/null & sleep 2; kill "$VSRV" 2>/dev/null; }
  [ -n "$OSRV" ] && kill "$OSRV" 2>/dev/null
  wait "$VSRV" "$OSRV" 2>/dev/null
  if [ "$KEEP" = 1 ]; then echo "run directory kept: $WORK"; else rm -rf "$WORK"; fi
}
trap cleanup EXIT

[ -x "$BIN" ]     || { echo "build first: cargo build --release -p terrustia --bin terrustia"; exit 1; }
[ -x "$PROBE" ]   || { echo "build first: cargo build --release -p terrustia --example probe"; exit 1; }
[ -x "$VANILLA" ] || { echo "no real server at: $VANILLA   (set TERRARIA_SERVER)"; exit 1; }

VPORT=$((20000 + RANDOM % 20000))
OPORT=$((VPORT + 1))
GPORT=$((VPORT + 2))

# Wait for a line to appear in a log rather than sleeping: vanilla's world generation takes as long
# as it takes, and a guessed sleep is how a run comes back with an empty probe and no explanation.
wait_for() { # wait_for <file> <text> <seconds> <pid>
  for _ in $(seq 1 "$3"); do
    grep -qF "$2" "$1" 2>/dev/null && return 0
    kill -0 "$4" 2>/dev/null || { echo "FAIL: process exited before '$2'"; tail -20 "$1"; return 1; }
    sleep 1
  done
  echo "FAIL: never saw '$2' in $1"; tail -20 "$1"; return 1
}

# ---------------------------------------------------------------- 1. one world, written by vanilla

cat > "$WORK/gen.txt" <<END
world=$WORK/base.wld
autocreate=1
seed=$SEED
worldname=diffworld
difficulty=0
maxplayers=8
port=$GPORT
secure=0
upnp=0
END

echo "=== generating the shared world with the real server (seed $SEED) ==="
mkfifo "$WORK/gfifo"
"$VANILLA" -config "$WORK/gen.txt" < "$WORK/gfifo" > "$WORK/gen.log" 2>&1 &
GEN=$!
exec 9> "$WORK/gfifo"
wait_for "$WORK/gen.log" "Server started" 600 "$GEN" || exit 1
echo exit >&9
for _ in $(seq 1 60); do kill -0 "$GEN" 2>/dev/null || break; sleep 1; done
kill "$GEN" 2>/dev/null
exec 9>&-
[ -s "$WORK/base.wld" ] || { echo "FAIL: the real server wrote no world"; tail -20 "$WORK/gen.log"; exit 1; }
cp "$WORK/base.wld" "$WORK/vanilla.wld"
cp "$WORK/base.wld" "$WORK/ours.wld"
echo "world: $(wc -c < "$WORK/base.wld" | tr -d ' ') bytes, one copy each"

# ---------------------------------------------------------------- 2. both servers on that world

cat > "$WORK/run.txt" <<END
world=$WORK/vanilla.wld
worldname=diffworld
difficulty=0
maxplayers=8
port=$VPORT
secure=0
upnp=0
END

mkfifo "$WORK/vfifo"
"$VANILLA" -config "$WORK/run.txt" < "$WORK/vfifo" > "$WORK/vanilla.log" 2>&1 &
VSRV=$!
exec 8> "$WORK/vfifo"
wait_for "$WORK/vanilla.log" "Server started" 300 "$VSRV" || exit 1
echo "real server up on $VPORT"

# An empty MOTD, because vanilla's is empty too and `greetPlayer` branches on it; anything else
# would be comparing our config against their default.
TERRUSTIA_MOTD="" \
  TERRUSTIA_UPNP_ENABLED=false \
  TERRUSTIA_UPDATE_CHECK_ENABLED=false \
  TERRUSTIA_PANEL_ENABLED=false \
  "$BIN" --headless --world "$WORK/ours.wld" --listen "127.0.0.1:$OPORT" \
  > "$WORK/ours.log" 2>&1 &
OSRV=$!
wait_for "$WORK/ours.log" "accepting connections" 300 "$OSRV" || exit 1
echo "terrustia up on $OPORT"

# ---------------------------------------------------------------- 3. probe each

echo "=== probing both (linger ${LINGER}s past packet 129) ==="
PROBE_LINGER="$LINGER" "$PROBE" "127.0.0.1:$VPORT" > "$WORK/vanilla.probe" 2>&1
PROBE_LINGER="$LINGER" "$PROBE" "127.0.0.1:$OPORT" > "$WORK/ours.probe"   2>&1

# "<-  49 InitialSpawn  0 bytes" -> "49 InitialSpawn 0"
seq_of() { grep '^<- ' "$1" | awk '{print $2, $3, $4}'; }
seq_of "$WORK/vanilla.probe" > "$WORK/vanilla.seq"
seq_of "$WORK/ours.probe"    > "$WORK/ours.seq"
[ -s "$WORK/vanilla.seq" ] || { echo "FAIL: the real server sent nothing"; cat "$WORK/vanilla.probe"; exit 1; }
[ -s "$WORK/ours.seq" ]    || { echo "FAIL: terrustia sent nothing";       cat "$WORK/ours.probe";    exit 1; }

# ---------------------------------------------------------------- 4. judge

fail=0
expected_id() { echo "$EXPECTED" | grep -qE "^$1( |\$)"; }
reason_for()  { echo "$EXPECTED" | grep -E "^$1( |\$)" | head -1 | cut -d' ' -f2-; }

# The join phase is everything up to and including the *first* 129, and it is the only part of a
# session two servers can be held to packet for packet. What comes after is two different
# simulations running for the same few seconds: whether a slime wandered into view, whether an item
# timed out, whether water settled. Judging that would fail on weather. So the join phase is judged
# and the live phase is reported.
split_at_129() { # split_at_129 <seq> <join-out> <live-out>; echoes the frame number of 129, or 0
  local at
  at=$(grep -n '^129 ' "$1" | head -1 | cut -d: -f1)
  if [ -z "$at" ]; then cp "$1" "$2"; : > "$3"; echo 0; return; fi
  head -n "$at" "$1" > "$2"
  tail -n +"$((at + 1))" "$1" > "$3"
  echo "$at"
}
V129=$(split_at_129 "$WORK/vanilla.seq" "$WORK/vanilla.join" "$WORK/vanilla.live")
O129=$(split_at_129 "$WORK/ours.seq"    "$WORK/ours.join"    "$WORK/ours.live")

echo ""
echo "=== 1. ORDER of the join phase (runs of one id collapsed; vanilla | terrustia) ==="
collapse() { awk '{ if ($1 != last) { if (n) printf "%s %s%s\n", last, lastname, (n>1 ? " x" n : ""); last=$1; lastname=$2; n=1 } else n++ }
                   END { if (n) printf "%s %s%s\n", last, lastname, (n>1 ? " x" n : "") }' "$1"; }
collapse "$WORK/vanilla.join" > "$WORK/vanilla.run"
collapse "$WORK/ours.join"    > "$WORK/ours.run"
paste -d'|' <(awk '{printf "%-34s\n", $0}' "$WORK/vanilla.run") "$WORK/ours.run"

echo ""
echo "--- the named invariant: the join tail must precede 129 FinishedConnectingToServer ---"
# 129 is "you are in". Vanilla sends it as the last act of `MessageBuffer` case 12
# (`MessageBuffer.cs:937`), after 139 (`:934`) and after `SyncConnectedPlayer` has sent 60, 72 and 74
# (`NetMessage.cs:2841-2856`); 101 and 136 went out earlier still, in case 8 (`:869-870`), before 49.
# So none of these can legitimately follow 129: a client that treats 129 as the end of the handshake
# never reads what comes after it.
#
# First occurrence, not last: 57 and 60 are also sent live, long after the join, by both servers.
for f in "$WORK/vanilla.seq:vanilla:$V129" "$WORK/ours.seq:terrustia:$O129"; do
  file="${f%%:*}"; rest="${f#*:}"; who="${rest%%:*}"; at129="${rest##*:}"
  if [ "$at129" = 0 ]; then
    echo "  FAIL  $who: never sent 129 at all"; fail=1; continue
  fi
  late=""
  for tail_id in 101 136 57 103 49 60 72 74 139; do
    first=$(grep -n "^$tail_id " "$file" | head -1 | cut -d: -f1)
    [ -n "$first" ] && [ "$first" -gt "$at129" ] && late="$late $tail_id"
  done
  if [ -z "$late" ]; then
    echo "  PASS  $who: 129 at frame $at129, the whole join tail ahead of it"
  else
    echo "  FAIL  $who: 129 at frame $at129, but these are first seen only after it:$late"; fail=1
  fi
done

echo ""
echo "=== 2. COVERAGE of the join phase (ids one server sends and the other never does) ==="
awk '{print $1, $2}' "$WORK/vanilla.join" | sort -u > "$WORK/vanilla.ids"
awk '{print $1, $2}' "$WORK/ours.join"    | sort -u > "$WORK/ours.ids"
only() { comm -23 "$1" "$2"; }
for side in "vanilla:$WORK/vanilla.ids:$WORK/ours.ids" "terrustia:$WORK/ours.ids:$WORK/vanilla.ids"; do
  who="${side%%:*}"; rest="${side#*:}"; mine="${rest%%:*}"; theirs="${rest##*:}"
  while read -r pid name; do
    [ -z "$pid" ] && continue
    if expected_id "$pid"; then
      echo "  note  only $who sends $pid $name  ($(reason_for "$pid"))"
    else
      echo "  FAIL  only $who sends $pid $name during the join"; fail=1
    fi
  done < <(only "$mine" "$theirs")
done
grep -q . <(only "$WORK/vanilla.ids" "$WORK/ours.ids"; only "$WORK/ours.ids" "$WORK/vanilla.ids") \
  || echo "  PASS  the join phases carry exactly the same set of packet ids"

echo ""
echo "=== 3. PAYLOAD of the join phase (frame count and byte lengths per id) ==="
# Counted and sized rather than compared byte for byte: `conform` below is the byte-level check, and
# it is the one that can tell a wrong field width from a different NPC.
census() { awk '{ c[$1 " " $2]++; if (!($1 in lo) || $3+0 < lo[$1]) lo[$1]=$3+0; if ($3+0 > hi[$1]) hi[$1]=$3+0 }
                 END { for (k in c) { split(k, p, " "); printf "%s %s %d %d %d\n", p[1], p[2], c[k], lo[p[1]], hi[p[1]] } }' "$1" | sort -n; }
census "$WORK/vanilla.join" > "$WORK/vanilla.census"
census "$WORK/ours.join"    > "$WORK/ours.census"
printf "  %-4s %-28s %14s   %14s\n" id name "vanilla n/bytes" "ours n/bytes"
join -a1 -a2 -j1 -o 0,1.2,2.2,1.3,1.4,1.5,2.3,2.4,2.5 -e - \
  <(sort -k1,1 "$WORK/vanilla.census") <(sort -k1,1 "$WORK/ours.census") \
  | sort -n | while read -r pid vname oname vn vlo vhi on olo ohi; do
      name="$vname"; [ "$name" = "-" ] && name="$oname"
      vcell="-"; [ "$vn" != "-" ] && vcell="$vn x ${vlo}..${vhi}"
      ocell="-"; [ "$on" != "-" ] && ocell="$on x ${olo}..${ohi}"
      mark="  "; [ "$vcell" != "$ocell" ] && mark="~ "
      printf "%s%-4s %-28s %14s   %14s\n" "$mark" "$pid" "$name" "$vcell" "$ocell"
    done

echo ""
echo "=== 4. LIVE traffic after 129, ${LINGER}s each (reported, never judged) ==="
live_hist() { awk '{c[$1 " " $2]++} END {for (k in c) print k, c[k]}' "$1" | sort -n; }
paste -d'|' <(live_hist "$WORK/vanilla.live" | awk '{printf "%-34s\n", $0}') <(live_hist "$WORK/ours.live")

# ---------------------------------------------------------------- 5. conform, past the handshake

CONFORM="$ROOT/target/release/examples/conform"
if [ -x "$CONFORM" ]; then
  echo ""
  echo "=== 5. CONFORM: decode and re-encode the real server's own bytes ==="
  # The point of running this against vanilla and not only against ourselves: our client and our
  # server share `terrustia-proto`, so a field read at the wrong width is read at the wrong width by
  # both and every one of our own tests still passes. Only bytes the game wrote can find that.
  for target in "vanilla:$VPORT" "terrustia:$OPORT"; do
    who="${target%%:*}"; port="${target##*:}"
    echo "--- $who ---"
    if "$CONFORM" "127.0.0.1:$port" "$WORK/$who.trcap" 12; then
      echo "  PASS  $who: every decodable frame re-encoded byte-identically"
    else
      echo "  FAIL  $who: see the mismatch above"; fail=1
    fi
  done
else
  echo ""
  echo "note  conform not built, so nothing past the handshake was checked at byte level."
  echo "      cargo build --release -p terrustia-client --example conform"
fi

echo ""
echo "=== VERDICT ==="
[ "$fail" -eq 0 ] && echo "=== differential PASSED ===" || echo "=== differential FAILED ==="
exit "$fail"
