#!/usr/bin/env python3
"""Generate crates/terrustia-proto/src/hurt_tiles.rs from TileID.Sets.

Which tiles hurt to stand in decides where a teleport may land. Getting it wrong is not subtle:
a magic conch that drops you into a bed of spikes, or a demon conch that lands you in lava, is
worse than one that does nothing.
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(sys.argv[1])
OUT = pathlib.Path(sys.argv[2])

tile_cs = (ROOT / "Terraria.ID/TileID.cs").read_text(errors="replace")
COUNT = int(re.search(r"public static readonly ushort Count = (\d+);", tile_cs).group(1))


def bool_set(name):
    m = re.search(rf"public static bool\[\] {name} = Factory\.CreateBoolSet\(([^)]*)\);", tile_cs)
    if not m:
        raise SystemExit(f"no bool set {name}")
    body = m.group(1).strip()
    if not body:
        return set()
    parts = [p.strip() for p in body.split(",") if p.strip()]
    assert parts[0] not in ("true", "false"), f"{name} flips its default"
    return {int(p) for p in parts}


def int_set(name):
    m = re.search(rf"public static int\[\] {name} = Factory\.CreateIntSet\(([^)]*)\);", tile_cs)
    if not m:
        raise SystemExit(f"no int set {name}")
    nums = [int(x) for x in re.findall(r"-?\d+", m.group(1))]
    default, rest = nums[0], nums[1:]
    values = {}
    for i in range(0, len(rest) - 1, 2):
        values[rest[i]] = rest[i + 1]
    return default, values


suffocate = bool_set("Suffocate")
bleeding = bool_set("TouchDamageBleeding")
hot = bool_set("TouchDamageHot")
default_immediate, immediate = int_set("TouchDamageImmediate")

# Two tiles hurt only under a world seed this server does not offer, so they never hurt here.
# `Collision.CanTileHurt` gates 230 on Ravaged and 80 on Don't Starve.
seed_only = {230, 80}

hurts = (suffocate | bleeding | hot | set(immediate)) - seed_only


def bool_table(name, members, doc):
    lines = [doc, f"pub const {name}: [bool; {COUNT}] = ["]
    row = []
    for i in range(COUNT):
        row.append("true," if i in members else "false,")
        if len(row) == 16:
            lines.append("    " + " ".join(row))
            row = []
    if row:
        lines.append("    " + " ".join(row))
    lines.append("];")
    return "\n".join(lines)


out = [
    '''//! Which tiles hurt to stand in, generated from the game's own sets.
//!
//! This decides where a teleport may put you. A magic conch that drops you into spikes, or a
//! demon conch that lands you in lava, is worse than one that does nothing at all — so the
//! landing-spot search consults this before it accepts a candidate.
//!
//! Two tiles the game can make dangerous are deliberately absent. `Collision.CanTileHurt` gates
//! tile 230 behind the Ravaged seed and tile 80 behind Don't Starve; this server offers neither,
//! so on it they are ordinary blocks.
//!
//! Generated by `tools/gen_hurt_tiles.py` from Terraria 1.4.5.7. Do not edit by hand.
''',
    bool_table(
        "HURTS",
        hurts,
        """
/// Whether standing in this tile costs you something.
///
/// The union of `TouchDamageBleeding`, `Suffocate`, `TouchDamageHot` and everything with a
/// non-zero `TouchDamageImmediate` — which is exactly what `Collision.CanTileHurt` answers true
/// for, minus the two seed-gated ones.""",
    ),
    bool_table(
        "SUFFOCATES",
        suffocate,
        """
/// The tiles that hurt by being *inside* them rather than by being touched.
///
/// The distinction matters to the collision box: the game shrinks the test by two pixels on each
/// side for these, so brushing past sand does not suffocate you.""",
    ),
    '''
/// Whether standing in this tile costs you something.
pub fn hurts(tile: u16) -> bool {
    HURTS.get(tile as usize).copied().unwrap_or(false)
}

/// Whether this tile hurts by enclosing rather than by touch.
pub fn suffocates(tile: u16) -> bool {
    SUFFOCATES.get(tile as usize).copied().unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Spot checks against tiles whose behaviour is unmistakable.
    #[test]
    fn the_obvious_hazards_are_hazards() {
        assert!(hurts(48), "spikes");
        assert!(hurts(232), "wooden spikes");
        assert!(hurts(37), "meteorite burns");
        assert!(hurts(58), "hellstone burns");
        assert!(hurts(53) || suffocates(53), "sand suffocates");
        assert!(!hurts(1), "stone is just stone");
        assert!(!hurts(0), "and so is dirt");
    }

    /// The two seed-gated tiles are ordinary here, because those seeds are not offered.
    #[test]
    fn the_seed_only_hazards_are_harmless() {
        assert!(!hurts(230), "tile 230 needs Ravaged");
        assert!(!hurts(80), "cactus needs Don't Starve");
    }

    /// Suffocating tiles are a subset of hurting ones, or the box-shrink rule applies to nothing.
    #[test]
    fn suffocating_tiles_also_hurt() {
        for tile in 0..super::HURTS.len() as u16 {
            if suffocates(tile) {
                assert!(hurts(tile), "tile {tile} suffocates but does not hurt");
            }
        }
    }
}
''',
]

OUT.write_text("\n".join(out) + "\n")
print(
    f"wrote {OUT}: {COUNT} tiles, {len(hurts)} that hurt "
    f"({len(suffocate)} suffocate, {len(bleeding)} bleed, {len(hot)} burn, "
    f"{len(immediate)} immediate)"
)
