#!/usr/bin/env python3
"""Generate crates/terrustia-proto/src/shimmer.rs from ItemID.Sets and NPCID.Sets.

Shimmer transmutes. An item dropped into it becomes another item, or a creature, or coin luck —
and which is entirely per-item data, hundreds of pairs of it, so it belongs in a table generated
from the game's rather than anywhere near hand-written code.
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(sys.argv[1])
OUT = pathlib.Path(sys.argv[2])

item_cs = (ROOT / "Terraria.ID/ItemID.cs").read_text(errors="replace")
npc_cs = (ROOT / "Terraria.ID/NPCID.cs").read_text(errors="replace")

ITEM_COUNT = int(re.search(r"public static readonly (?:short|int) Count = (\d+);", item_cs).group(1))
NPC_COUNT = int(re.search(r"public static readonly (?:short|int) Count = (\d+);", npc_cs).group(1))


def int_set(text, name):
    """`Factory.CreateIntSet(default, key, value, key, value, ...)` as a dict."""
    m = re.search(rf"public static int\[\] {name} = Factory\.CreateIntSet\(([^;]*?)\);", text, re.S)
    if not m:
        raise SystemExit(f"no int set {name}")
    nums = [int(x) for x in re.findall(r"-?\d+", m.group(1))]
    default, rest = nums[0], nums[1:]
    if len(rest) % 2:
        raise SystemExit(f"{name} has an odd tail; the parse is wrong")
    return default, {rest[i]: rest[i + 1] for i in range(0, len(rest), 2)}


def bool_set(text, name):
    m = re.search(rf"public static bool\[\] {name} = Factory\.CreateBoolSet\(([^)]*)\);", text)
    if not m:
        raise SystemExit(f"no bool set {name}")
    body = m.group(1).strip()
    if not body:
        return set()
    parts = [p.strip() for p in body.split(",") if p.strip()]
    assert parts[0] not in ("true", "false"), name
    return {int(p) for p in parts}


_, transform = int_set(item_cs, "ShimmerTransformToItem")
_, counts_as = int_set(item_cs, "ShimmerCountsAsItem")
coins = bool_set(item_cs, "CommonCoin")
_, to_npc = int_set(npc_cs, "ShimmerTransformToNPC")

if len(transform) < 200:
    raise SystemExit(f"only {len(transform)} transforms parsed; the set's shape changed")


def pairs_table(name, mapping, count, ty, doc):
    """A sorted (key, value) table, which is much smaller than a full array for a sparse set."""
    rows = sorted((k, v) for k, v in mapping.items() if 0 <= k < count and v > 0)
    lines = [doc, f"const {name}: [({ty}, {ty}); {len(rows)}] = ["]
    row = []
    for k, v in rows:
        row.append(f"({k},{v}),")
        if len(row) == 8:
            lines.append("    " + " ".join(row))
            row = []
    if row:
        lines.append("    " + " ".join(row))
    lines.append("];")
    return "\n".join(lines)


out = [
    '''//! What shimmer turns things into, generated from the game's own tables.
//!
//! Shimmer transmutes. An item dropped into it becomes another item, or a creature, or — for
//! coins — luck. Which of those, and into what, is per-item data running to several hundred
//! pairs, so it lives here rather than anywhere near hand-written code.
//!
//! One branch of the game's shimmer is deliberately absent: **decrafting**. An item with no
//! transform and no creature falls back to being broken into its recipe's ingredients, which
//! needs the whole recipe database — thousands of entries, and a system this server does not
//! model at all. An item that would decraft simply does not shimmer here. That is a gap and is
//! recorded as one in `docs/shimmer.md` rather than papered over with a guess.
//!
//! Generated by `tools/gen_shimmer.py` from Terraria 1.4.5.7. Do not edit by hand.
''',
    pairs_table(
        "TRANSFORMS",
        transform,
        ITEM_COUNT,
        "u16",
        """
/// `ItemID.Sets.ShimmerTransformToItem`: what an item becomes.
///
/// Sorted by item id so it can be searched rather than indexed — it is a few hundred pairs out
/// of several thousand items, and a full array would be mostly zeroes.""",
    ),
    pairs_table(
        "COUNTS_AS",
        counts_as,
        ITEM_COUNT,
        "u16",
        """
/// `ItemID.Sets.ShimmerCountsAsItem`: items that shimmer as though they were another.
///
/// Checked first, so a variant transmutes the way the thing it stands in for does.""",
    ),
    pairs_table(
        "NPC_TRANSFORMS",
        to_npc,
        NPC_COUNT,
        "u16",
        """
/// `NPCID.Sets.ShimmerTransformToNPC`: a creature let out of a jar becomes another creature.""",
    ),
]

out.append(
    f"""
/// The coins, whose shimmer is luck rather than an item. `ItemID.Sets.CommonCoin`.
pub const COPPER_COIN: u16 = {min(coins) if coins else 71};
"""
)

out.append(
    """
fn look_up(table: &[(u16, u16)], key: u16) -> Option<u16> {
    table
        .binary_search_by_key(&key, |&(k, _)| k)
        .ok()
        .map(|at| table[at].1)
}

/// The item this one shimmers *as*, which is usually itself.
///
/// A handful of variants stand in for another item so they transmute the way it does. The game
/// calls this `GetShimmerEquivalentType`.
pub fn equivalent(item: u16) -> u16 {
    look_up(&COUNTS_AS, item).unwrap_or(item)
}

/// What an item becomes in shimmer, if it becomes another item.
pub fn transforms_into(item: u16) -> Option<u16> {
    look_up(&TRANSFORMS, equivalent(item))
}

/// What a caught creature becomes when its jar goes in.
pub fn npc_becomes(npc_type: u16) -> Option<u16> {
    look_up(&NPC_TRANSFORMS, npc_type)
}

/// Whether an item is a coin, whose shimmer is coin luck rather than a transformation.
///
/// The four are consecutive and always have been, which is why this is a range rather than a
/// table of four entries.
pub fn is_coin(item: u16) -> bool {
    (COPPER_COIN..COPPER_COIN + 4).contains(&item)
}

/// What a stack of coins is worth in coppers, for the luck it grants.
///
/// Silver is a hundred coppers, gold ten thousand, platinum a million — and platinum is capped
/// at one, which is the game's own rule and stops a stack of them being worth a billion.
pub fn coin_luck(item: u16, stack: i32) -> i32 {
    match item.checked_sub(COPPER_COIN) {
        Some(0) => stack,
        Some(1) => stack.saturating_mul(100),
        Some(2) => stack.saturating_mul(10_000),
        Some(3) => 1_000_000,
        _ => 0,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Both tables are sorted, or the binary searches above silently miss.
    #[test]
    fn the_tables_are_sorted() {
        for (name, table) in [
            ("TRANSFORMS", &TRANSFORMS[..]),
            ("COUNTS_AS", &COUNTS_AS[..]),
            ("NPC_TRANSFORMS", &NPC_TRANSFORMS[..]),
        ] {
            assert!(
                table.windows(2).all(|w| w[0].0 < w[1].0),
                "{name} must be strictly ascending by key"
            );
        }
    }

    /// Spot checks against transmutations that are well known.
    #[test]
    fn the_known_transmutations_hold() {
        // A Gold Chest's key mould line, and the ore/bar pairs, are the ones players learn first.
        assert_eq!(transforms_into(9), Some(2), "wood becomes stone");
        assert!(transforms_into(1).is_none(), "an iron pickaxe does not");
    }

    /// Coins are luck, and the four of them are worth what they are worth.
    #[test]
    fn coins_are_worth_their_weight() {
        assert!(is_coin(COPPER_COIN));
        assert!(is_coin(COPPER_COIN + 3));
        assert!(!is_coin(COPPER_COIN + 4));
        assert_eq!(coin_luck(COPPER_COIN, 50), 50);
        assert_eq!(coin_luck(COPPER_COIN + 1, 5), 500);
        assert_eq!(coin_luck(COPPER_COIN + 2, 5), 50_000);
        assert_eq!(
            coin_luck(COPPER_COIN + 3, 99),
            1_000_000,
            "platinum is capped at one, however many are thrown in"
        );
        assert_eq!(coin_luck(1, 5), 0, "and a pickaxe is not a coin");
    }

    /// A stack big enough to overflow is saturated rather than wrapped.
    #[test]
    fn an_absurd_stack_does_not_wrap() {
        assert_eq!(coin_luck(COPPER_COIN + 2, i32::MAX), i32::MAX);
    }

    /// An item that stands in for another transmutes the way that other one does.
    #[test]
    fn a_stand_in_follows_what_it_stands_for() {
        for &(variant, real) in COUNTS_AS.iter() {
            assert_eq!(
                equivalent(variant),
                real,
                "item {variant} should shimmer as {real}"
            );
            assert_eq!(transforms_into(variant), transforms_into(real));
        }
    }
}
"""
)

OUT.write_text("\n".join(out) + "\n")
print(
    f"wrote {OUT}: {len(transform)} item transforms, {len(counts_as)} stand-ins, "
    f"{len(to_npc)} creature transforms, {len(coins)} coins"
)
