#!/usr/bin/env python3
"""Generate crates/terrustia-proto/src/travel_shop.rs from Chest.SetupTravelShop_GetItem.

The Travelling Merchant's stock is chosen by a chain of luck rolls — one per candidate item, each
overwriting the last, so the *final* match wins. Which item, at which rarity, and under which
world condition is per-item data, so it is parsed rather than transcribed.
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(sys.argv[1])
OUT = pathlib.Path(sys.argv[2])

chest_cs = (ROOT / "Terraria/Chest.cs").read_text(errors="replace")

start = chest_cs.index("public static void SetupTravelShop_GetItem(")
end = chest_cs.index("public static void SetupTravelShop()", start)
body = chest_cs[start:end]

# `if (playerWithHighestLuck.RollLuck(rarity[N]) == 0 [&& cond...]) { it = ITEM; }`
pattern = re.compile(
    r"if \(playerWithHighestLuck\.RollLuck\(rarity\[(\d+)\]\) == 0([^)]*)\)\s*\{\s*it = (\d+);",
    re.S,
)
# The `minimumRarity` guards partition the chain; track the floor in force at each match.
floors = [(m.start(), int(m.group(1))) for m in re.finditer(r"if \(minimumRarity > (\d+)\)", body)]

CONDITIONS = {
    "Main.hardMode": "HARDMODE",
    "NPC.downedMechBossAny": "ANY_MECH",
    "NPC.downedMechBoss1": "DESTROYER",
    "NPC.downedMechBoss2": "TWINS",
    "NPC.downedMechBoss3": "PRIME",
    "NPC.downedBoss1": "EYE",
    "NPC.downedBoss3": "SKELETRON",
    "WorldGen.shadowOrbSmashed": "ORB_SMASHED",
}

entries = []
for m in pattern.finditer(body):
    tier = int(m.group(1))
    tail = m.group(2)
    item = int(m.group(3))
    # A nested RollLuck in the tail means a compound roll this table cannot express; skip it and
    # say so rather than emitting something that looks right.
    if "RollLuck" in tail:
        continue
    needs = [flag for src, flag in CONDITIONS.items() if src in tail]
    # Which minimumRarity floor is in force here.
    floor = 0
    for at, value in floors:
        if at < m.start():
            floor = value
    entries.append((tier, item, needs, floor))

if len(entries) < 30:
    raise SystemExit(f"only {len(entries)} shop entries parsed; the chain's shape changed")

flags = sorted({f for _, _, needs, _ in entries for f in needs})

lines = [
    '''//! The Travelling Merchant's stock, generated from the game's own chain.
//!
//! His inventory is not a list but a *chain of rolls*: one per candidate item, each overwriting
//! the last, so the final match wins. Rarer items sit at higher tiers and are rolled against
//! longer odds, and several only appear once the world has been through something.
//!
//! Generated by `tools/gen_travel_shop.py` from Terraria 1.4.5.7. Do not edit by hand.

/// What a world must already have been through for an item to be offered.
///
/// A bit set rather than an enum: a few items want two things at once.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Needs(pub u16);

impl Needs {
    pub const NONE: Self = Self(0);
''',
]
for i, flag in enumerate(flags):
    lines.append(f"    pub const {flag}: u16 = 1 << {i};")
lines.append(
    """
    pub fn met_by(self, world: Needs) -> bool {
        self.0 & !world.0 == 0
    }
}

/// One thing the merchant might be carrying.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Offer {
    pub item: u16,
    /// Which rarity tier's odds it is rolled against. Higher is rarer.
    pub tier: u8,
    /// What the world must have been through.
    pub needs: Needs,
    /// The `minimumRarity` floor below which the game stops considering this part of the chain.
    pub floor: u8,
}
"""
)

lines.append(f"/// The chain, in the order the game walks it. Later entries win.")
lines.append(f"pub const OFFERS: [Offer; {len(entries)}] = [")
for tier, item, needs, floor in entries:
    bits = " | ".join(f"Needs::{f}" for f in needs) if needs else "0"
    lines.append(
        f"    Offer {{ item: {item}, tier: {tier}, needs: Needs({bits}), floor: {floor} }},"
    )
lines.append("];")

lines.append(
    '''
/// How many rarity tiers there are, and the odds each is rolled against.
///
/// `Chest.SetupTravelShop`'s starting array. The odds are one-in-N, so a tier-five item at 1200
/// turns up about once in every twelve hundred rolls of that step.
pub const TIER_ODDS: [i32; 6] = [1, 1, 1, 6, 300, 1200];

#[cfg(test)]
mod tests {
    use super::*;

    /// Every offer names a real item and a tier the odds table has.
    #[test]
    fn every_offer_is_well_formed() {
        for offer in OFFERS {
            assert!(offer.item > 0, "an offer with no item");
            assert!(
                (offer.tier as usize) < TIER_ODDS.len(),
                "item {} names tier {}, past the odds table",
                offer.item,
                offer.tier
            );
        }
    }

    /// A fresh world can be offered something, and a finished one can be offered more.
    #[test]
    fn progress_widens_the_stock() {
        let open = |world: Needs| {
            OFFERS
                .iter()
                .filter(|o| o.needs.met_by(world))
                .count()
        };
        let fresh = open(Needs::NONE);
        let late = open(Needs(u16::MAX));
        assert!(fresh > 0, "a fresh world should have stock");
        assert!(late > fresh, "{late} late against {fresh} fresh");
    }

    /// The condition test is a subset check, not equality: a world that has been through more
    /// than an item asks for still qualifies.
    #[test]
    fn extra_progress_does_not_disqualify() {
        let wants = Needs(Needs::HARDMODE);
        assert!(wants.met_by(Needs(Needs::HARDMODE)));
        assert!(wants.met_by(Needs(u16::MAX)));
        assert!(!wants.met_by(Needs::NONE));
    }
}
'''
)

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT}: {len(entries)} offers, {len(flags)} conditions ({', '.join(flags)})")
