#!/usr/bin/env python3
"""Generate crates/terrustia-proto/src/town_names.rs from the game's own name lists.

A town NPC without a name is not a cosmetic gap: the client shows the type's name where a given
name should be, so every guide in the world is "Guide" and none of them is Andrew. The lists live
in the localisation files rather than in code, and `NPC.getNewNPCNameInner` maps each type to one.
"""
import json
import re
import sys
import pathlib

ROOT = pathlib.Path(sys.argv[1])
OUT = pathlib.Path(sys.argv[2])

npc_cs = (ROOT / "Terraria/NPC.cs").read_text(errors="replace")
town_json = (ROOT / "Terraria.Localization.Content.en-US.Town.json").read_text(errors="replace")

# The localisation files carry trailing commas, which JSON proper does not allow.
cleaned = re.sub(r",(\s*[}\]])", r"\1", town_json)
data = json.loads(cleaned)

# type -> category, straight out of getNewNPCNameInner's switch.
start = npc_cs.index("private static string getNewNPCNameInner")
end = npc_cs.index("public NetworkText GetTypeNetName", start)
switch = npc_cs[start:end]
pairs = re.findall(r"(\d+) => Language\.RandomFromCategory\(\"([A-Za-z_]+)\"", switch)
if len(pairs) < 30:
    raise SystemExit(f"only {len(pairs)} name categories parsed; the switch shape changed")


def names_in(category):
    node = data.get(category)
    if node is None:
        raise SystemExit(f"category {category} is not in the localisation file")
    return list(node.values())


entries = []
for npc_type, category in pairs:
    entries.append((int(npc_type), category, names_in(category)))
entries.sort()

# Three types are not one creature but six: a cat, a dog and a bunny each roll a breed, and the
# breed decides both how it looks and which list its name comes from. The breeds are registered
# in TownNPCProfiles rather than in the name switch, so they are read from there.
profiles_cs = (ROOT / "Terraria.GameContent/TownNPCProfiles.cs").read_text(errors="replace")
variants = []
for m in re.finditer(
    r"\{\s*(\d+),\s*new Profiles\.VariantNPCProfile\(\s*\"[^\"]*\",\s*\"([A-Za-z]+)\",\s*"
    r"[A-Za-z]+,\s*((?:\"[A-Za-z]+\"(?:,\s*)?)+)\)",
    profiles_cs,
):
    npc_type = int(m.group(1))
    base = m.group(2)
    breeds = re.findall(r'"([A-Za-z]+)"', m.group(3))
    variants.append((npc_type, base, [(b, names_in(f"{base}Names_{b}")) for b in breeds]))
variants.sort()
if not variants:
    raise SystemExit("no variant profiles parsed; TownNPCProfiles' shape changed")

lines = [
    '''//! The names town NPCs are given, generated from the game's own lists.
//!
//! A town NPC carries a name of its own on top of its type, and the client asks the server for
//! it the moment the NPC comes into view. Left unanswered, every guide in the world is "Guide"
//! and no two of them can be told apart.
//!
//! The lists are the localisation file's, and which list a type draws from is
//! `NPC.getNewNPCNameInner`. Generated by `tools/gen_town_names.py` from Terraria 1.4.5.7. Do
//! not edit by hand.
''',
]

emitted = set()
for npc_type, category, names in entries:
    const = re.sub(r"[^A-Z0-9]", "_", category.upper())
    emitted.add(const)
    lines.append(f"/// `{category}`, for NPC type {npc_type}.")
    lines.append(f"const {const}: [&str; {len(names)}] = [")
    row = []
    for n in names:
        row.append(json.dumps(n) + ",")
        if sum(len(x) for x in row) > 80:
            lines.append("    " + " ".join(row))
            row = []
    if row:
        lines.append("    " + " ".join(row))
    lines.append("];")
    lines.append("")

lines.append(
    """/// Which list a type draws its name from, in type order.
const LISTS: [(u16, &[&str]); %d] = ["""
    % len(entries)
)
for npc_type, category, _ in entries:
    const = re.sub(r"[^A-Z0-9]", "_", category.upper())
    lines.append(f"    ({npc_type}, &{const}),")
lines.append("];")
lines.append("")

for npc_type, base, breeds in variants:
    for breed, names in breeds:
        const = re.sub(r"[^A-Z0-9]", "_", f"{base}Names_{breed}".upper())
        # The first breed's list is also the type's default and has already been emitted.
        if const in emitted:
            continue
        emitted.add(const)
        lines.append(f"/// `{base}Names_{breed}`.")
        lines.append(f"const {const}: [&str; {len(names)}] = [")
        row = []
        for n in names:
            row.append(json.dumps(n) + ",")
            if sum(len(x) for x in row) > 80:
                lines.append("    " + " ".join(row))
                row = []
        if row:
            lines.append("    " + " ".join(row))
        lines.append("];")
        lines.append("")

lines.append(
    """/// The types that are not one creature but several, and the name list each breed uses.
///
/// A cat, a dog and a bunny each roll a breed on arrival; the breed decides how it looks and
/// which names it can have, which is why the two cannot be chosen independently.
const BREEDS: [(u16, &[&[&str]]); %d] = ["""
    % len(variants)
)
for npc_type, base, breeds in variants:
    inner = ", ".join(
        "&" + re.sub(r"[^A-Z0-9]", "_", f"{base}Names_{breed}".upper()) for breed, _ in breeds
    )
    lines.append(f"    ({npc_type}, &[{inner}]),")
lines.append("];")

lines.append(
    '''
/// The names a type may be given, or an empty slice if it is not the kind of NPC that has one.
///
/// Every NPC has a *type* name; this is the personal one on top of it, which only town NPCs,
/// town pets and town slimes carry.
pub fn names_for(npc_type: u16) -> &'static [&'static str] {
    match LISTS.binary_search_by_key(&npc_type, |&(ty, _)| ty) {
        Ok(at) => LISTS[at].1,
        Err(_) => &[],
    }
}

/// Whether a type is given a personal name at all.
pub fn has_given_name(npc_type: u16) -> bool {
    !names_for(npc_type).is_empty()
}

/// How many looks a type has to choose between when it arrives.
///
/// One for almost everything. Six for the cat, the dog and the bunny, whose breed is rolled on
/// arrival and then decides both the sprite and the name list.
pub fn variation_count(npc_type: u16) -> usize {
    match BREEDS.binary_search_by_key(&npc_type, |&(ty, _)| ty) {
        Ok(at) => BREEDS[at].1.len(),
        Err(_) => 1,
    }
}

/// The names a type may be given once its look has been chosen.
///
/// For everything but the three pets this is exactly [`names_for`]; for those it is the chosen
/// breed's own list, because a Siamese is never called Rex.
pub fn names_for_variation(npc_type: u16, variation: usize) -> &'static [&'static str] {
    if let Ok(at) = BREEDS.binary_search_by_key(&npc_type, |&(ty, _)| ty)
        && let Some(names) = BREEDS[at].1.get(variation)
    {
        return names;
    }
    names_for(npc_type)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The list is sorted, or the binary search above silently misses.
    #[test]
    fn the_lists_are_in_type_order() {
        assert!(
            LISTS.windows(2).all(|w| w[0].0 < w[1].0),
            "LISTS must be strictly ascending by type"
        );
    }

    /// The types the game names, and the ones it does not.
    #[test]
    fn the_named_types_are_the_town_ones() {
        assert!(has_given_name(22), "the guide has a name");
        assert!(has_given_name(17), "so does the merchant");
        assert!(has_given_name(637), "and the cat");
        assert!(!has_given_name(1), "a green slime does not");
        assert!(!has_given_name(0), "and neither does nothing");
    }

    /// Every list has something in it, and nothing in it is blank.
    #[test]
    fn every_list_holds_real_names() {
        for (ty, names) in LISTS {
            assert!(!names.is_empty(), "type {ty} has an empty name list");
            assert!(
                names.iter().all(|n| !n.trim().is_empty()),
                "type {ty} has a blank name"
            );
        }
    }

    /// The guide's list is the one the game ships, spot-checked against a name from it.
    #[test]
    fn the_guide_can_be_andrew() {
        assert!(names_for(22).contains(&"Andrew"));
    }

    /// The pets have six breeds each; everything else has one look.
    #[test]
    fn only_the_pets_have_breeds() {
        assert!(BREEDS.windows(2).all(|w| w[0].0 < w[1].0));
        for (ty, breeds) in BREEDS {
            assert_eq!(breeds.len(), 6, "type {ty} should have six breeds");
        }
        assert_eq!(variation_count(22), 1, "the guide has one look");
        assert_eq!(variation_count(637), 6, "the cat has six");
    }

    /// A breed's names are its own, not the type's first list.
    #[test]
    fn a_breed_draws_from_its_own_names() {
        let first = names_for_variation(637, 0);
        let last = names_for_variation(637, 5);
        assert!(!first.is_empty() && !last.is_empty());
        assert_ne!(first, last, "two breeds should not share a name list");
        assert_eq!(
            names_for_variation(637, 0),
            names_for(637),
            "the first breed is the type's default list"
        );
        assert_eq!(
            names_for_variation(637, 99),
            names_for(637),
            "an impossible breed falls back rather than panicking"
        );
    }
}
'''
)

OUT.write_text("\n".join(lines) + "\n")
total = sum(len(n) for _, _, n in entries)
print(f"wrote {OUT}: {len(entries)} types, {total} names")
