#!/usr/bin/env python3
"""Generate `banners.rs` from `BannerSystem` and `ItemID.Sets.KillsToBanner`.

    python3 tools/gen_banners.py <decompiled-tree> crates/terrustia-proto/src/banners.rs

Nothing counted kills at all, so the fifty-kill banner rewards never arrived and the world file's
banner section was written as two zeroes with a comment saying as much. Banners are not
progression, but they are one of the few things a player *notices* the absence of: kill a hundred
zombies and the game is supposed to say something.

Three tables, and all three are per-type data rather than an algorithm:

* `NPCtoBanner` — a switch of a few hundred cases, NPC type to banner index.
* `BannerToItem` — banner index to item, written as a run of ranges rather than a table.
* `KillsToBanner` — how many kills each banner needs, fifty by default with a few dozen overrides.
"""

import re
import sys
from pathlib import Path


def parse_npc_to_banner(root: Path) -> dict[int, int]:
    """`case <npc>: return <banner>;`, allowing several cases to share one return."""
    text = (root / "Terraria.GameContent" / "BannerSystem.cs").read_text(errors="replace")
    body = text[text.index("public static int NPCtoBanner") :]
    body = body[: body.index("\n\tpublic ", 10)]

    out: dict[int, int] = {}
    pending: list[int] = []
    for line in body.splitlines():
        line = line.strip()
        if m := re.match(r"case (-?\d+):", line):
            pending.append(int(m.group(1)))
        elif m := re.match(r"return (\d+);", line):
            for npc in pending:
                if npc >= 0:
                    out[npc] = int(m.group(1))
            pending = []
        elif line in ("default:", "}"):
            pending = []
    return out


def parse_kills(root: Path) -> tuple[int, dict[int, int]]:
    """The default threshold and the per-item overrides."""
    text = (root / "Terraria.ID" / "ItemID.cs").read_text(errors="replace")
    default = int(
        re.search(r"DefaultKillsForBannerNeeded = (\d+);", text).group(1)
    )
    line = re.search(r"KillsToBanner = Factory\.CreateIntSet\(([^;]*)\);", text).group(1)
    # The first argument is the *name* `DefaultKillsForBannerNeeded`, not a number, so every digit
    # on the line is already part of an (item, kills) pair. Skipping one — the obvious reading —
    # shifts the whole list and pairs each item with the next item's threshold.
    numbers = [int(n) for n in re.findall(r"-?\d+", line)]
    if len(numbers) % 2 != 0:
        raise SystemExit(f"KillsToBanner has {len(numbers)} numbers, which cannot pair up")
    overrides = {numbers[i]: numbers[i + 1] for i in range(0, len(numbers), 2)}
    return default, overrides


def banner_to_item(banner: int) -> int:
    """`BannerSystem.BannerToItem`, which is a ladder of ranges rather than a table."""
    if banner == 292:
        return 5673
    if banner == 291:
        return 5672
    if banner >= 274:
        return 4687 + banner - 274
    if banner == 273:
        return 4602
    if banner >= 267:
        return 4541 + banner - 267
    if banner >= 257:
        return 3837 + banner - 257
    if banner >= 252:
        return 3789 + banner - 252
    if banner == 251:
        return 3780
    if banner >= 249:
        return 3593 + banner - 249
    if banner >= 186:
        return 3390 + banner - 186
    if banner >= 88:
        return 2897 + banner - 88
    return 1615 + banner - 1


def emit(npc_banner: dict[int, int], default: int, overrides: dict[int, int]) -> str:
    rows = sorted(npc_banner.items())
    lines = [
        "//! Which enemies have a banner, and how many of them it takes to earn one.",
        "//!",
        "//! Nothing counted kills before this, so the banner rewards never arrived and the world",
        "//! file's banner section was written as two zeroes. Not progression — but one of the few",
        "//! absences a player notices directly, because killing a hundred of something is supposed",
        "//! to be remarked upon.",
        "//!",
        "//! Generated by `tools/gen_banners.py`. Do not edit by hand.",
        "",
        "/// Kills needed when a banner says nothing else.",
        f"pub const DEFAULT_KILLS: u32 = {default};",
        "",
        f"/// How many enemy types have a banner at all.",
        f"pub const WITH_BANNERS: usize = {len(rows)};",
        "",
        "/// The banner index for an enemy type, if it has one.",
        "pub fn banner_of(npc_type: u16) -> Option<u16> {",
        "    Some(match npc_type {",
    ]
    for npc, banner in rows:
        lines.append(f"        {npc} => {banner},")
    lines += [
        "        _ => return None,",
        "    })",
        "}",
        "",
        "/// The item a banner index hands over.",
        "///",
        "/// A ladder of ranges rather than a table, exactly as `BannerSystem.BannerToItem` writes",
        "/// it — the banner items are laid out in runs across several id blocks.",
        "pub fn banner_item(banner: u16) -> u16 {",
        "    match banner {",
        "        292 => 5673,",
        "        291 => 5672,",
        "        b if b >= 274 => 4687 + b - 274,",
        "        273 => 4602,",
        "        b if b >= 267 => 4541 + b - 267,",
        "        b if b >= 257 => 3837 + b - 257,",
        "        b if b >= 252 => 3789 + b - 252,",
        "        251 => 3780,",
        "        b if b >= 249 => 3593 + b - 249,",
        "        b if b >= 186 => 3390 + b - 186,",
        "        b if b >= 88 => 2897 + b - 88,",
        "        b => 1615 + b - 1,",
        "    }",
        "}",
        "",
        "/// How many kills that banner's item asks for.",
        "pub fn kills_needed(item: u16) -> u32 {",
        "    match item {",
    ]
    for item, kills in sorted(overrides.items()):
        lines.append(f"        {item} => {kills},")
    lines += [
        "        _ => DEFAULT_KILLS,",
        "    }",
        "}",
        "",
        "#[cfg(test)]",
        "mod tests {",
        "    use super::*;",
        "",
        "    /// The table is populated and did not regenerate empty.",
        "    #[test]",
        "    fn the_table_is_populated() {",
        f"        assert_eq!(WITH_BANNERS, {len(rows)});",
        "    }",
        "",
        "    /// A zombie has a banner and a slime does not, which is the shape of the set.",
        "    #[test]",
        "    fn ordinary_enemies_have_banners() {",
        "        let zombie = banner_of(3).expect(\"a zombie has a banner\");",
        "        let item = banner_item(zombie);",
        "        assert!(item > 0);",
        "        assert!(kills_needed(item) >= 10);",
        "    }",
        "",
        "    /// Something with no banner says so rather than guessing one.",
        "    #[test]",
        "    fn not_everything_has_a_banner() {",
        "        assert!(banner_of(u16::MAX).is_none());",
        "    }",
        "",
        "    /// Every banner maps to a distinct item, or two enemies would share a reward.",
        "    #[test]",
        "    fn banners_do_not_collide() {",
        "        let mut items = std::collections::HashSet::new();",
        "        let mut banners: Vec<u16> = (0..700u16).filter_map(banner_of).collect();",
        "        banners.sort_unstable();",
        "        banners.dedup();",
        "        for banner in banners {",
        "            assert!(",
        "                items.insert(banner_item(banner)),",
        "                \"banner {banner} shares an item with another\",",
        "            );",
        "        }",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 1
    root, out = Path(sys.argv[1]), Path(sys.argv[2])
    npc_banner = parse_npc_to_banner(root)
    default, overrides = parse_kills(root)
    if len(npc_banner) < 100:
        print(f"error: only parsed {len(npc_banner)} banners; the parser is wrong", file=sys.stderr)
        return 1
    out.write_text(emit(npc_banner, default, overrides))
    print(f"wrote {len(npc_banner)} banner mappings and {len(overrides)} thresholds to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
