#!/usr/bin/env python3
"""Generate crates/terrustia-proto/src/angler.rs from Main.AnglerQuestSwap.

The Angler asks for one of forty-one fish each dawn, but not every fish is available in every
world at every point: some only exist in hardmode, some only in one evil or the other, and three
need a boss to have fallen. The rules are a run of guard clauses in `AnglerQuestSwap`; parsing
them keeps the table honest rather than hand-transcribed.
"""
import re
import sys
import pathlib

ROOT = pathlib.Path(sys.argv[1])
OUT = pathlib.Path(sys.argv[2])

main_cs = (ROOT / "Terraria/Main.cs").read_text(errors="replace")

# The list of fish, in the order the roll indexes it.
m = re.search(r"public static int\[\] anglerQuestItemNetIDs = new int\[(\d+)\]\s*\{(.*?)\};",
              main_cs, re.S)
count = int(m.group(1))
fish = [int(x) for x in re.findall(r"\d+", m.group(2))]
if len(fish) != count:
    raise SystemExit(f"expected {count} fish, parsed {len(fish)}")

# The guard clauses. Everything up to the `isThereAWorldSurface` branch, which only fires under
# world seeds this server does not offer.
start = main_cs.index("public static void AnglerQuestSwap()")
body = main_cs[start : main_cs.index("if (!isThereAWorldSurface)", start)]

# `if (num == N && <condition>) { flag2 = true; }` means "reroll when <condition>", i.e. the fish
# is *unavailable* when the condition holds. Turn each into what the fish requires.
rules = {}
for m in re.finditer(r"if \(num == (\d+) && ([^)]*(?:\([^)]*\))?[^)]*)\)", body):
    item = int(m.group(1))
    cond = m.group(2)
    needs = rules.setdefault(item, {"hardmode": False, "evil": None, "any_boss": False})
    # "reroll if !hardMode" -> needs hardmode
    if "!hardMode" in cond:
        needs["hardmode"] = True
    # "reroll if crimson" -> needs corruption; "reroll if !crimson" -> needs crimson
    if re.search(r"!WorldGen\.crimson", cond):
        needs["evil"] = "crimson"
    elif re.search(r"WorldGen\.crimson", cond):
        needs["evil"] = "corruption"

# The three that need a boss down are gated by a separate combined clause.
boss_clause = re.search(r"if \(\(([^)]*)\) && !flag\)", body)
if boss_clause:
    for item in (int(x) for x in re.findall(r"num == (\d+)", boss_clause.group(1))):
        rules.setdefault(item, {"hardmode": False, "evil": None, "any_boss": False})
        rules[item]["any_boss"] = True

if len(rules) < 10:
    raise SystemExit(f"only {len(rules)} gated fish parsed; AnglerQuestSwap's shape changed")


def evil_of(item):
    r = rules.get(item)
    if not r or r["evil"] is None:
        return "Either"
    return "Crimson" if r["evil"] == "crimson" else "Corruption"


lines = [
    '''//! The Angler's daily quest, generated from the game's own rules.
//!
//! One of forty-one fish is asked for each dawn, but not every fish is catchable in every world:
//! some only exist in hardmode, some only in one evil or the other, and three want a boss to have
//! fallen first. Asking for a fish that cannot be caught is not a small bug — it costs the player
//! a whole day of a reward track.
//!
//! Generated by `tools/gen_angler.py` from Terraria 1.4.5.7. Do not edit by hand.

/// Which evil a fish needs the world to have.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Evil {
    /// Catchable either way.
    Either,
    Corruption,
    Crimson,
}

/// One fish the Angler may ask for.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Quest {
    /// The item the fish is.
    pub item: i32,
    /// Whether the world must be in hardmode.
    pub hardmode: bool,
    /// Which evil the world must have, if it matters.
    pub evil: Evil,
    /// Whether some boss must already have fallen.
    pub any_boss: bool,
}
''',
    f"/// Every fish, in the order the daily roll indexes them.\npub const QUESTS: [Quest; {count}] = [",
]

for item in fish:
    r = rules.get(item, {"hardmode": False, "evil": None, "any_boss": False})
    lines.append(
        f"    Quest {{ item: {item}, hardmode: {str(r['hardmode']).lower()}, "
        f"evil: Evil::{evil_of(item)}, any_boss: {str(r['any_boss']).lower()} }},"
    )
lines.append("];")

lines.append(
    '''
/// Whether a fish can be asked for in a world in this state.
pub fn available(quest: &Quest, hardmode: bool, crimson: bool, any_boss_downed: bool) -> bool {
    if quest.hardmode && !hardmode {
        return false;
    }
    match quest.evil {
        Evil::Either => {}
        Evil::Crimson if !crimson => return false,
        Evil::Corruption if crimson => return false,
        _ => {}
    }
    if quest.any_boss && !any_boss_downed {
        return false;
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A fresh world can still be given a quest, or the Angler is useless until hardmode.
    #[test]
    fn a_fresh_world_has_fish_to_ask_for() {
        let open = QUESTS
            .iter()
            .filter(|q| available(q, false, false, false))
            .count();
        assert!(open > 10, "only {open} fish available in a fresh world");
    }

    /// Hardmode opens more than pre-hardmode, not fewer.
    #[test]
    fn hardmode_opens_more_fish() {
        let before = QUESTS
            .iter()
            .filter(|q| available(q, false, false, true))
            .count();
        let after = QUESTS
            .iter()
            .filter(|q| available(q, true, false, true))
            .count();
        assert!(after > before, "{after} in hardmode against {before} before");
    }

    /// The two evils each lock some fish and open others, and neither locks everything.
    #[test]
    fn each_evil_has_its_own_fish() {
        let corruption: Vec<i32> = QUESTS
            .iter()
            .filter(|q| available(q, true, false, true))
            .map(|q| q.item)
            .collect();
        let crimson: Vec<i32> = QUESTS
            .iter()
            .filter(|q| available(q, true, true, true))
            .map(|q| q.item)
            .collect();
        assert_ne!(corruption, crimson, "the evils should differ");
        assert!(corruption.iter().any(|i| !crimson.contains(i)));
        assert!(crimson.iter().any(|i| !corruption.contains(i)));
    }

    /// Every fish is a real item id and none is listed twice.
    #[test]
    fn the_fish_are_distinct_items() {
        let mut seen = std::collections::HashSet::new();
        for quest in QUESTS {
            assert!(quest.item > 0, "a fish with no item");
            assert!(seen.insert(quest.item), "item {} listed twice", quest.item);
        }
    }
}
'''
)

OUT.write_text("\n".join(lines) + "\n")
gated = sum(1 for f in fish if f in rules)
print(f"wrote {OUT}: {count} fish, {gated} with conditions")
